FROM     debian:bookworm AS builder_debian12
LABEL Description="Build environment Debian 12"

ENV HOME /root

SHELL ["/bin/bash", "-c"]

RUN apt-get update; \
    apt-get -y --no-install-recommends install \
    gcc g++ build-essential cmake wget \
    dpkg libarchive-dev liblz4-dev liblzma-dev libedit-dev libncurses5-dev \
    libasound2-dev pkg-config;
